"""add exclude analysis to sample

Revision ID: 01071cc1f73a
Revises: 57eb9fc479a8
Create Date: 2017-05-09 15:54:40.944272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01071cc1f73a'
down_revision = '57eb9fc479a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('exclude_analysis', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'exclude_analysis')
    # ### end Alembic commands ###
