"""add comment field allow null for status

Revision ID: 4f952373811d
Revises: ae4cba78038c
Create Date: 2017-03-09 14:03:04.312879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f952373811d'
down_revision = 'ae4cba78038c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('sample', 'status',
               existing_type=mysql.ENUM('affected', 'unaffected', 'unknown'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'status',
               existing_type=mysql.ENUM('affected', 'unaffected', 'unknown'),
               nullable=False)
    op.drop_column('sample', 'comment')
    # ### end Alembic commands ###
