"""add fields to invoice table

Revision ID: 666effe598f2
Revises: 7420a714c773
Create Date: 2017-04-06 11:27:07.750486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666effe598f2'
down_revision = '7420a714c773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('_data', sa.Text(), nullable=True))
    op.add_column('invoice', sa.Column('costcenter', sa.Enum('kth', 'ki'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'costcenter')
    op.drop_column('invoice', '_data')
    # ### end Alembic commands ###
