"""add boolean field to mark existing families

Revision ID: 6c8b7f5cde7d
Revises: a21fdb1a4314
Create Date: 2017-05-02 11:36:54.939831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8b7f5cde7d'
down_revision = 'a21fdb1a4314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('existing_family', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family', 'existing_family')
    # ### end Alembic commands ###
