"""add comment columns

Revision ID: 7420a714c773
Revises: 4f952373811d
Create Date: 2017-03-28 11:10:10.804687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7420a714c773'
down_revision = '4f952373811d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationtag', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('applicationtag', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('applicationtag_version', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('method', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('method', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('method', 'last_updated')
    op.drop_column('method', 'comment')
    op.drop_column('applicationtag_version', 'last_updated')
    op.drop_column('applicationtag', 'last_updated')
    op.drop_column('applicationtag', 'comment')
    # ### end Alembic commands ###
