"""require invoice id to be unique

Revision ID: 75e036b103b8
Revises: 666effe598f2
Create Date: 2017-04-07 14:38:02.431378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e036b103b8'
down_revision = '666effe598f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invoice', ['invoice_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='unique')
    # ### end Alembic commands ###
