"""add comment and custom excel file for invoice

Revision ID: a21fdb1a4314
Revises: 75e036b103b8
Create Date: 2017-04-13 12:53:03.981111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21fdb1a4314'
down_revision = '75e036b103b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('invoice', sa.Column('excel_file_ki', sa.BLOB(), nullable=True))
    op.add_column('invoice', sa.Column('excel_file_kth', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'excel_file_kth')
    op.drop_column('invoice', 'excel_file_ki')
    op.drop_column('invoice', 'comment')
    # ### end Alembic commands ###
