"""add project LIMS id to model

Revision ID: b9a793f4a131
Revises: 8a1f6acace77
Create Date: 2017-02-16 14:19:56.784198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a793f4a131'
down_revision = '8a1f6acace77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('lims_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'lims_id')
    # ### end Alembic commands ###
