"""send sent date to invoice

Revision ID: c9e97d4c09c2
Revises: e17af8950075
Create Date: 2017-05-09 09:38:34.521741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e97d4c09c2'
down_revision = 'e17af8950075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'sent_at')
    # ### end Alembic commands ###
